"use client";

import { Bell, Pencil, Plus, Trash2 } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import type { Reminder, ReminderType } from "@/domain/personal";
import { Input } from "@/components/motion/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/motion/select";
import { Switch } from "@/components/motion/switch";
import { reminderRepository } from "@/lib/storage/repositories";
import { nextReminderOccurrence, sanitizeReminderLabel } from "@/lib/reminders";

const types: Array<{ value: ReminderType; label: string }> = [{ value: "prayer", label: "صلاة" }, { value: "quran", label: "قراءة القرآن" }, { value: "morning-adhkar", label: "أذكار الصباح" }, { value: "evening-adhkar", label: "أذكار المساء" }, { value: "kahf", label: "سورة الكهف" }, { value: "custom", label: "ورد شخصي" }];
const days = [{ value: 6, label: "س" }, { value: 0, label: "ح" }, { value: 1, label: "ن" }, { value: 2, label: "ث" }, { value: 3, label: "ر" }, { value: 4, label: "خ" }, { value: 5, label: "ج" }];
const formatter = new Intl.DateTimeFormat("ar-SA", { weekday: "long", hour: "numeric", minute: "2-digit" });

export default function RemindersPage() {
  const [items, setItems] = useState<Reminder[]>([]); const [editingId, setEditingId] = useState<string | null>(null); const [type, setType] = useState<ReminderType>("quran"); const [label, setLabel] = useState("ورد القرآن"); const [time, setTime] = useState("20:00"); const [selectedDays, setSelectedDays] = useState<number[]>([0, 1, 2, 3, 4, 5, 6]); const [offset, setOffset] = useState("0");
  const refresh = () => void reminderRepository.list().then(setItems); useEffect(refresh, []);
  const next = useMemo(() => items.map((item) => ({ item, date: nextReminderOccurrence(item) })).filter((entry): entry is { item: Reminder; date: Date } => Boolean(entry.date)).sort((a, b) => a.date.getTime() - b.date.getTime())[0], [items]);
  function reset() { setEditingId(null); setType("quran"); setLabel("ورد القرآن"); setTime("20:00"); setSelectedDays([0, 1, 2, 3, 4, 5, 6]); setOffset("0"); }
  async function save(event: React.FormEvent) { event.preventDefault(); const clean = sanitizeReminderLabel(label); if (!clean || selectedDays.length === 0) return; const existing = editingId ? items.find((item) => item.id === editingId) : undefined; await reminderRepository.save({ id: editingId ?? crypto.randomUUID(), type, label: clean, enabled: existing?.enabled ?? true, time, days: selectedDays, timezone: Intl.DateTimeFormat().resolvedOptions().timeZone, prayerOffsetMinutes: type === "prayer" ? Number(offset) : undefined, createdAt: existing?.createdAt ?? new Date().toISOString() }); refresh(); reset(); }
  function edit(item: Reminder) { setEditingId(item.id); setType(item.type); setLabel(item.label); setTime(item.time); setSelectedDays(item.days); setOffset(String(item.prayerOffsetMinutes ?? 0)); }
  return <main><header className="page-intro"><p className="eyebrow text-accent">التذكيرات</p><h1>تذكير لطيف، في وقته</h1><p>تُحفظ الجداول محليًا. إشعار الخلفية بعد إغلاق المتصفح لا يعمل إلا عند إعداد Web Push على الخادم ومنح الإذن.</p></header>{next && <section className="next-reminder"><span>التذكير القادم</span><h2>{next.item.label}</h2><p>{formatter.format(next.date)}</p></section>}
    <form onSubmit={save} className="reminder-form"><Select value={type} onValueChange={(value) => setType(value as ReminderType)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{types.map((entry) => <SelectItem key={entry.value} value={entry.value}>{entry.label}</SelectItem>)}</SelectContent></Select><Input value={label} onChange={setLabel} placeholder="اسم التذكير" maxLength={80} /><input className="time-input" type="time" value={time} onChange={(event) => setTime(event.target.value)} aria-label="وقت التذكير" />{type === "prayer" && <Select value={offset} onValueChange={setOffset}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="0">عند وقت الصلاة</SelectItem><SelectItem value="-5">قبلها بـ 5 دقائق</SelectItem><SelectItem value="-10">قبلها بـ 10 دقائق</SelectItem><SelectItem value="-15">قبلها بـ 15 دقيقة</SelectItem></SelectContent></Select>}<fieldset className="weekday-picker"><legend>أيام التكرار</legend>{days.map((day) => <button key={day.value} type="button" aria-pressed={selectedDays.includes(day.value)} onClick={() => setSelectedDays((current) => current.includes(day.value) ? current.filter((value) => value !== day.value) : [...current, day.value])}>{day.label}</button>)}</fieldset><button type="submit" className="primary-link"><Plus className="size-4" />{editingId ? "حفظ التعديل" : "إضافة التذكير"}</button></form>
    <section className="reminder-list" aria-label="التذكيرات المحفوظة">{items.map((item) => <article key={item.id} className="reminder-row"><Bell /><div><h2>{item.label}</h2><p>{types.find((entry) => entry.value === item.type)?.label} · <span dir="ltr">{item.time}</span> · {item.days.length === 7 ? "يوميًا" : `${item.days.length} أيام`}</p></div><Switch checked={item.enabled} onCheckedChange={(enabled) => void reminderRepository.save({ ...item, enabled }).then(refresh)} aria-label={`تفعيل ${item.label}`} /><button type="button" onClick={() => edit(item)} aria-label={`تعديل ${item.label}`}><Pencil /></button><button type="button" onClick={() => void reminderRepository.remove(item.id).then(refresh)} aria-label={`حذف ${item.label}`}><Trash2 /></button></article>)}</section>{!items.length && <div className="compact-empty"><Bell /><h2>لا توجد تذكيرات بعد</h2><p>أضف أول تذكير واختر أيامه ووقته.</p></div>}
  </main>;
}
