"use client";
import { Bookmark, Pause, Play } from "lucide-react";
import { useMemo, useState } from "react";
import type { AudioTrack, Reciter } from "@/domain/audio";
import type { QuranChapter } from "@/domain/quran";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/motion/select";
import { savedRepository, historyRepository } from "@/lib/storage/repositories";
import { useAudioPlayer } from "@/stores/audio-player";

export function ReciterProfile({ reciter, chapters }: { reciter: Reciter; chapters: QuranChapter[] }) { const [moshafId, setMoshafId] = useState(String(reciter.moshaf[0]?.id ?? "")); const moshaf = reciter.moshaf.find((entry) => entry.id === Number(moshafId)) ?? reciter.moshaf[0]; const current = useAudioPlayer((state) => state.track); const playing = useAudioPlayer((state) => state.isPlaying); const play = useAudioPlayer((state) => state.play); const toggle = useAudioPlayer((state) => state.toggle); const queue = useMemo<AudioTrack[]>(() => moshaf ? chapters.filter((chapter) => moshaf.availableSurahs.includes(chapter.id)).map((chapter) => ({ id: `mp3quran-${reciter.id}-${moshaf.id}-${chapter.id}`, url: `${moshaf.server.replace(/\/$/, "")}/${String(chapter.id).padStart(3, "0")}.mp3`, title: chapter.nameArabic, reciter: reciter.name, reciterId: reciter.id, riwayah: moshaf.name, surahId: chapter.id, surahName: chapter.nameArabic, provider: "MP3Quran API v3" })) : [], [chapters, moshaf, reciter.id, reciter.name]); function start(track: AudioTrack) { void historyRepository.record({ id: `reciter:${reciter.id}`, type: "reciter", title: reciter.name, href: `/reciters/${reciter.id}`, viewedAt: new Date().toISOString() }); if (current?.id === track.id) toggle(); else play(track, queue); } return <><div className="reciter-profile-head"><div className="reciter-avatar">{reciter.name.slice(0,1)}</div><div><p className="eyebrow">القارئ</p><h1>{reciter.name}</h1><p>{queue.length} سورة متاحة</p></div><button type="button" onClick={() => void savedRepository.save({ id: `reciter:${reciter.id}`, type: "reciter", title: reciter.name, href: `/reciters/${reciter.id}`, provider: reciter.provider, sourceUrl: reciter.sourceUrl, createdAt: new Date().toISOString() })}><Bookmark />حفظ القارئ</button></div><div className="reciter-moshaf"><span>الرواية / المصحف</span><Select value={moshafId} onValueChange={setMoshafId}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{reciter.moshaf.map((entry) => <SelectItem key={entry.id} value={String(entry.id)}>{entry.name}</SelectItem>)}</SelectContent></Select></div><section className="surah-audio-list">{queue.map((track) => { const active = current?.id === track.id; return <article key={track.id}><span>{track.surahId}</span><div><h2>{track.title}</h2><p>{track.riwayah}</p></div><button type="button" onClick={() => start(track)} aria-label={`${active && playing ? "إيقاف" : "تشغيل"} ${track.title}`}>{active && playing ? <Pause /> : <Play />}</button></article>; })}</section><p className="source-line">المصدر: <a href={reciter.sourceUrl} target="_blank" rel="noreferrer">{reciter.provider}</a></p></>; }
