"use client";
import Link from "next/link";
import { Headphones, Pause, Play, Search } from "lucide-react";
import { useMemo, useState } from "react";
import type { AudioTrack, Reciter } from "@/domain/audio";
import type { QuranChapter } from "@/domain/quran";
import { Input } from "@/components/motion/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/motion/select";
import { normalizeArabicSearch } from "@/lib/islamic/search";
import { useAudioPlayer } from "@/stores/audio-player";

function trackFor(reciter: Reciter, chapter: QuranChapter): AudioTrack | null { const moshaf = reciter.moshaf.find((item) => item.availableSurahs.includes(chapter.id)); if (!moshaf) return null; return { id: `mp3quran-${reciter.id}-${moshaf.id}-${chapter.id}`, url: `${moshaf.server.replace(/\/$/, "")}/${String(chapter.id).padStart(3, "0")}.mp3`, title: chapter.nameArabic, reciter: reciter.name, reciterId: reciter.id, riwayah: moshaf.name, surahId: chapter.id, surahName: chapter.nameArabic, provider: "MP3Quran API v3" }; }
export function ReciterBrowser({ reciters, chapters }: { reciters: Reciter[]; chapters: QuranChapter[] }) { const [query, setQuery] = useState(""); const [surahId, setSurahId] = useState("1"); const current = useAudioPlayer((state) => state.track); const playing = useAudioPlayer((state) => state.isPlaying); const play = useAudioPlayer((state) => state.play); const toggle = useAudioPlayer((state) => state.toggle); const chapter = chapters.find((item) => item.id === Number(surahId)) ?? chapters[0]; const visible = useMemo(() => reciters.filter((reciter) => normalizeArabicSearch(reciter.name).includes(normalizeArabicSearch(query)) && Boolean(chapter && trackFor(reciter, chapter))), [chapter, query, reciters]); return <><div className="listen-controls"><Input value={query} onChange={setQuery} placeholder="ابحث باسم القارئ" leftIcon={<Search />} className="flex-1" /><Select value={surahId} onValueChange={setSurahId} className="z-10 w-full sm:w-64"><SelectTrigger><SelectValue placeholder="اختر السورة" /></SelectTrigger><SelectContent className="max-h-80 overflow-y-auto">{chapters.map((item) => <SelectItem key={item.id} value={String(item.id)}>{item.nameArabic}</SelectItem>)}</SelectContent></Select></div><p className="mt-4 text-sm text-muted-foreground">يتوفر {visible.length.toLocaleString("ar-SA")} قارئ لهذه السورة.</p><div className="reciter-grid">{visible.map((reciter) => { const track = chapter ? trackFor(reciter, chapter) : null; if (!track) return null; const active = current?.id === track.id; return <article className="reciter-card" key={track.id}><Link href={`/reciters/${reciter.id}`} className="reciter-avatar">{reciter.name.slice(0, 1)}</Link><div className="min-w-0 flex-1"><h2><Link href={`/reciters/${reciter.id}`}>{reciter.name}</Link></h2><p>{track.riwayah} · {track.title}</p></div><button onClick={() => active ? toggle() : play(track)} aria-label={`${active && playing ? "إيقاف" : "تشغيل"} ${track.title} بصوت ${reciter.name}`}>{active && playing ? <Pause /> : <Play />}</button></article>; })}</div>{visible.length === 0 && <div className="compact-empty"><Headphones className="size-6" /><h2>لا تتوفر تلاوة مطابقة</h2><p>جرّب قارئًا أو سورة أخرى.</p></div>}<p className="source-line">المصدر: <a href="https://mp3quran.net/ar/api" target="_blank" rel="noreferrer">MP3Quran API v3</a></p></>; }
