"use client";

import { BookOpenText, Languages, LoaderCircle, TextCursorInput } from "lucide-react";
import { useEffect, useState } from "react";
import type { QuranResourceOption, QuranVerseStudy } from "@/domain/quran";
import { BottomSheet } from "@/components/motion/bottom-sheet";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/motion/select";

type Resources = { tafsirs: QuranResourceOption[]; translations: QuranResourceOption[] };

export function VerseStudySheet({ verseKey, chapterName }: { verseKey: string; chapterName: string }) {
  const [open, setOpen] = useState(false); const [resources, setResources] = useState<Resources | null>(null); const [tafsirId, setTafsirId] = useState(""); const [translationId, setTranslationId] = useState(""); const [study, setStudy] = useState<QuranVerseStudy | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  useEffect(() => { if (!open || resources) return; setLoading(true); fetch("/api/quran/resources").then(async (response) => { const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setResources(payload); const savedTafsir = localStorage.getItem("dhu-al-jalal:tafsir"); const savedTranslation = localStorage.getItem("dhu-al-jalal:translation"); setTafsirId(savedTafsir && payload.tafsirs.some((item: QuranResourceOption) => String(item.id) === savedTafsir) ? savedTafsir : String(payload.tafsirs[0]?.id ?? "")); setTranslationId(savedTranslation && payload.translations.some((item: QuranResourceOption) => String(item.id) === savedTranslation) ? savedTranslation : ""); }).catch((reason) => setError(reason instanceof Error ? reason.message : "تعذر تحميل الموارد")).finally(() => setLoading(false)); }, [open, resources]);
  useEffect(() => { if (!open || (!tafsirId && !translationId)) return; const timer = window.setTimeout(() => { setLoading(true); setError(""); const params = new URLSearchParams(); if (tafsirId) { params.set("tafsir", tafsirId); localStorage.setItem("dhu-al-jalal:tafsir", tafsirId); } if (translationId) { params.set("translation", translationId); localStorage.setItem("dhu-al-jalal:translation", translationId); } fetch(`/api/quran/verse/${verseKey}?${params}`).then(async (response) => { const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setStudy(payload); }).catch((reason) => setError(reason instanceof Error ? reason.message : "تعذر تحميل المحتوى")).finally(() => setLoading(false)); }, 180); return () => window.clearTimeout(timer); }, [open, tafsirId, translationId, verseKey]);
  return <><button type="button" onClick={() => setOpen(true)} aria-label="فتح التفسير والترجمة"><BookOpenText /></button><BottomSheet open={open} onOpenChange={setOpen} snapPoints={[0.72, 0.94]} title={`تفسير ${chapterName} · ${verseKey}`} description="محتوى موثق من Islamic App والمورد المختار"><div className="study-sheet"><div className="study-selectors"><Select value={tafsirId} onValueChange={setTafsirId}><SelectTrigger><SelectValue placeholder="اختر التفسير" /></SelectTrigger><SelectContent>{resources?.tafsirs.map((item) => <SelectItem key={item.id} value={String(item.id)}>{item.name}</SelectItem>)}</SelectContent></Select><Select value={translationId} onValueChange={setTranslationId}><SelectTrigger><SelectValue placeholder="ترجمة اختيارية" /></SelectTrigger><SelectContent>{resources?.translations.map((item) => <SelectItem key={item.id} value={String(item.id)}>{item.name}</SelectItem>)}</SelectContent></Select></div>{loading && <div className="study-loading"><LoaderCircle className="animate-spin" />جارٍ التحميل</div>}{error && <div className="compact-empty"><p>{error}</p><small>يبقى نص القرآن متاحًا، ولا نعرض تفسيرًا بديلًا غير موثق.</small></div>}{study?.tafsir && <section><header><BookOpenText /><div><h3>{study.tafsir.resourceName ?? "التفسير"}</h3><p>{study.tafsir.languageName}</p></div></header><p>{study.tafsir.text}</p></section>}{study?.translation && <section className="notranslate" translate="no"><header><Languages /><div><h3>{study.translation.resourceName ?? "الترجمة"}</h3><p>{study.translation.languageName}</p></div></header><p>{study.translation.text}</p></section>}{study?.words?.length && <section><header><TextCursorInput /><div><h3>كلمة بكلمة</h3><p>النص، النقل الصوتي، والمعنى كما يورده المصدر</p></div></header><div className="word-study-grid">{study.words.map((word) => <div key={word.position}><strong>{word.textUthmani}</strong>{word.transliteration && <span>{word.transliteration}</span>}{word.translation && <small>{word.translation}</small>}{word.audioUrl && <audio controls preload="none" src={word.audioUrl} aria-label={`صوت كلمة ${word.textUthmani}`} />}</div>)}</div></section>}{study && <footer className="content-attribution"><span>{study.provider}</span><a href={study.sourceUrl} target="_blank" rel="noreferrer">عرض الآية في المصدر</a></footer>}</div></BottomSheet></>;
}
