"use client";

import { Compass, LocateFixed, Rotate3D } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { normalizeDegrees, relativeQiblaDirection } from "@/lib/islamic/qibla";

interface CompassOrientationEvent extends DeviceOrientationEvent { webkitCompassHeading?: number; }
interface OrientationPermission { requestPermission?: () => Promise<"granted" | "denied">; }

export function QiblaCompass() {
  const [bearing, setBearing] = useState<number | null>(null); const [heading, setHeading] = useState<number | null>(null); const [sensorState, setSensorState] = useState<"idle" | "active" | "unavailable" | "denied">("idle"); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const onOrientation = useCallback((event: DeviceOrientationEvent) => { const compass = event as CompassOrientationEvent; const nextHeading = compass.webkitCompassHeading ?? (event.alpha === null ? null : normalizeDegrees(360 - event.alpha)); if (nextHeading !== null && Number.isFinite(nextHeading)) { setHeading(nextHeading); setSensorState("active"); } }, []);
  useEffect(() => () => window.removeEventListener("deviceorientation", onOrientation, true), [onOrientation]);
  async function enableSensor() { if (!("DeviceOrientationEvent" in window)) { setSensorState("unavailable"); return; } const permissionApi = DeviceOrientationEvent as unknown as OrientationPermission; try { if (permissionApi.requestPermission && await permissionApi.requestPermission() !== "granted") { setSensorState("denied"); return; } window.addEventListener("deviceorientation", onOrientation, true); window.setTimeout(() => setSensorState((current) => current === "idle" ? "unavailable" : current), 1800); } catch { setSensorState("denied"); } }
  function locate() { setLoading(true); setError(""); navigator.geolocation.getCurrentPosition(async ({ coords }) => { try { const response = await fetch(`/api/qibla?lat=${coords.latitude}&lng=${coords.longitude}`); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setBearing(payload.direction); localStorage.setItem("dhu-al-jalal:qibla", JSON.stringify({ direction: payload.direction, updatedAt: Date.now() })); } catch (reason) { setError(reason instanceof Error ? reason.message : "تعذر تحديد القبلة"); } finally { setLoading(false); } }, () => { setError("تعذر الوصول إلى الموقع. فعّل الإذن ثم حاول مرة أخرى."); setLoading(false); }, { maximumAge: 3_600_000, timeout: 12_000 }); }
  useEffect(() => { try { const saved = JSON.parse(localStorage.getItem("dhu-al-jalal:qibla") ?? "null") as { direction: number } | null; if (saved && Number.isFinite(saved.direction)) setBearing(saved.direction); } catch { localStorage.removeItem("dhu-al-jalal:qibla"); } }, []);
  const relative = bearing === null ? 0 : heading === null ? bearing : relativeQiblaDirection(bearing, heading);
  return <main><header className="page-intro"><p className="eyebrow text-accent">القبلة</p><h1>بوصلة حيّة، واتجاه ثابت</h1><p>يُطلب اتجاه القبلة مرة واحدة. بعد ذلك يغيّر حساس الهاتف العرض محليًا دون اتصالات إضافية.</p></header><div className="qibla-stage">{bearing === null ? <><Compass className="size-12 text-accent" /><h2>حدّد موقعك لعرض الاتجاه</h2><p>بعد حساب الزاوية يبقى اتجاه ثابت متاحًا حتى لو لم يدعم الجهاز حساس البوصلة.</p><button onClick={locate} disabled={loading} className="primary-link"><LocateFixed className="size-4" />{loading ? "جارٍ الحساب…" : "تحديد اتجاه القبلة"}</button></> : <><div className="compass-face" style={{ transform: heading === null ? undefined : `rotate(${-heading}deg)` }}><div className="compass-arrow" style={{ transform: `rotate(${heading === null ? bearing : bearing}deg)` }}><span>القبلة</span></div><div className="compass-center" /></div><h2>{bearing.toFixed(1)}° من الشمال</h2>{heading !== null ? <p>اتجه بالسهم إلى أعلى الشاشة · اتجاه الهاتف {heading.toFixed(0)}° · الانحراف {relative.toFixed(0)}°</p> : <p>هذه قراءة ثابتة من الشمال. فعّل حساس الهاتف للحصول على توجيه حي.</p>}{sensorState !== "active" && <button type="button" onClick={() => void enableSensor()} className="primary-link"><Rotate3D className="size-4" />تفعيل البوصلة الحيّة</button>}{sensorState === "unavailable" && <p className="error-text">الحساس غير متاح؛ استخدم زاوية الشمال الثابتة.</p>}{sensorState === "denied" && <p className="error-text">لم يُمنح إذن حساس الحركة. يمكنك تغييره من إعدادات المتصفح.</p>}<details className="calibration-help"><summary>مساعدة المعايرة</summary><p>حرّك الهاتف على هيئة الرقم 8 بعيدًا عن المعادن والأجهزة الكهربائية، ثم ضعه أفقيًا.</p></details><button onClick={locate} className="text-action">إعادة حساب الموقع</button><p className="source-line">المصدر: AlAdhan / Islamic Network</p></>}{error && <p role="alert" className="error-text">{error}</p>}</div></main>;
}
