"use client";
import { useEffect, useState } from "react";
import { Database, Moon, Palette, Shield, Sun, Volume2 } from "lucide-react";
import { useTheme } from "next-themes";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/motion/tabs";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/motion/select";
import { Switch } from "@/components/motion/switch";
import { STORE_NAMES, clearStore } from "@/lib/storage/indexed-db";
import { useAudioPlayer } from "@/stores/audio-player";

type Preferences = { readingMode: "mushaf" | "reading" | "tajweed"; mushafId: 1 | 19; quranSize: string; tafsir: string; translation: string; playbackSpeed: string; calculationMethod: string; asrSchool: string; hour12: boolean; history: boolean };
const defaults: Preferences = { readingMode: "mushaf", mushafId: 1, quranSize: "100", tafsir: "ar-tafsir-muyassar", translation: "none", playbackSpeed: "1", calculationMethod: "4", asrSchool: "0", hour12: false, history: true };
const KEY = "dhu-al-jalal:preferences";
const sizeFormatter = new Intl.NumberFormat("ar-SA", { style: "unit", unit: "megabyte", maximumFractionDigits: 1 });

export default function SettingsPage() { const { theme, setTheme } = useTheme(); const setSpeed = useAudioPlayer((state) => state.setSpeed); const [preferences, setPreferences] = useState(defaults); const [usage, setUsage] = useState("—"); const [message, setMessage] = useState(""); useEffect(() => { try { setPreferences({ ...defaults, ...JSON.parse(localStorage.getItem(KEY) ?? "{}") }); } catch { localStorage.removeItem(KEY); } void navigator.storage?.estimate().then((result) => setUsage(sizeFormatter.format((result.usage ?? 0) / 1_048_576))); }, []); function update<K extends keyof Preferences>(key: K, value: Preferences[K]) { const next = { ...preferences, [key]: value }; setPreferences(next); localStorage.setItem(KEY, JSON.stringify(next)); if (key === "playbackSpeed") setSpeed(Number(value)); }
  async function clearOffline() { if ("caches" in window) await Promise.all((await caches.keys()).map((key) => caches.delete(key))); setMessage("مُسحت ذاكرة المحتوى دون اتصال"); }
  async function clearAll() { await Promise.all(STORE_NAMES.map((store) => clearStore(store))); Object.keys(localStorage).filter((key) => key.startsWith("dhu-al-jalal:")).forEach((key) => localStorage.removeItem(key)); setPreferences(defaults); setMessage("مُسحت بيانات التطبيق المحلية"); }
  return <main><header className="page-intro"><p className="eyebrow text-accent">الإعدادات</p><h1>على طريقتك</h1><p>تُحفظ اختيارات الضيف على هذا الجهاز، ولا يحتاج الاستخدام الأساسي إلى حساب.</p></header><Tabs defaultValue="appearance"><TabsList className="settings-tabs"><TabsTrigger value="appearance">المظهر</TabsTrigger><TabsTrigger value="quran">القرآن</TabsTrigger><TabsTrigger value="audio">الصوت</TabsTrigger><TabsTrigger value="prayer">الصلاة</TabsTrigger><TabsTrigger value="storage">التخزين والخصوصية</TabsTrigger></TabsList>
    <TabsContent value="appearance" className="settings-section"><SettingHeader icon={<Palette />} title="المظهر" description="الداكن هو الافتراضي لأول زيارة، ويبقى اختيارك الصريح محفوظًا." /><div className="theme-grid">{[["dark", "داكن", Moon], ["light", "فاتح", Sun], ["system", "النظام", Palette]].map(([value, label, Icon]) => { const ThemeIcon = Icon as typeof Moon; return <button key={value as string} onClick={() => setTheme(value as string)} aria-pressed={theme === value}><ThemeIcon /><span>{label as string}</span></button>; })}</div></TabsContent>
    <TabsContent value="quran" className="settings-section"><SettingHeader icon={<Moon />} title="القرآن" description="اختيارات العرض لا تعدّل النص القرآني نفسه." /><SettingRow label="وضع القراءة الافتراضي"><Select value={preferences.readingMode} onValueChange={(value) => update("readingMode", value as Preferences["readingMode"])}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="mushaf">المصحف</SelectItem><SelectItem value="reading">القراءة</SelectItem><SelectItem value="tajweed">التجويد</SelectItem></SelectContent></Select></SettingRow><SettingRow label="نوع المصحف"><Select value={String(preferences.mushafId)} onValueChange={(value) => update("mushafId", Number(value) as 1 | 19)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="1">حفص — QCF V2</SelectItem><SelectItem value="19">التجويد — QCF V4</SelectItem></SelectContent></Select></SettingRow><SettingRow label="حجم العرض"><Select value={preferences.quranSize} onValueChange={(value) => update("quranSize", value)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="90">صغير</SelectItem><SelectItem value="100">متوسط</SelectItem><SelectItem value="115">كبير</SelectItem><SelectItem value="130">كبير جدًا</SelectItem></SelectContent></Select></SettingRow></TabsContent>
    <TabsContent value="audio" className="settings-section"><SettingHeader icon={<Volume2 />} title="الصوت" description="تُطبّق السرعة فورًا على المشغل العام." /><SettingRow label="سرعة التشغيل"><Select value={preferences.playbackSpeed} onValueChange={(value) => update("playbackSpeed", value)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{["0.75", "1", "1.25", "1.5", "2"].map((value) => <SelectItem key={value} value={value}>{value}×</SelectItem>)}</SelectContent></Select></SettingRow></TabsContent>
    <TabsContent value="prayer" className="settings-section"><SettingHeader icon={<Sun />} title="الصلاة" description="يمكن تعديلها أيضًا مباشرة من صفحة الصلاة." /><SettingRow label="طريقة الحساب"><Select value={preferences.calculationMethod} onValueChange={(value) => update("calculationMethod", value)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="4">أم القرى</SelectItem><SelectItem value="3">رابطة العالم الإسلامي</SelectItem><SelectItem value="2">ISNA</SelectItem><SelectItem value="5">الهيئة المصرية</SelectItem></SelectContent></Select></SettingRow><SettingRow label="حساب العصر"><Select value={preferences.asrSchool} onValueChange={(value) => update("asrSchool", value)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="0">الجمهور</SelectItem><SelectItem value="1">الحنفي</SelectItem></SelectContent></Select></SettingRow><SettingRow label="نظام 12 ساعة"><Switch checked={preferences.hour12} onCheckedChange={(value) => update("hour12", value)} /></SettingRow></TabsContent>
    <TabsContent value="storage" className="settings-section"><SettingHeader icon={<Database />} title="التخزين" description={`الاستخدام التقريبي على هذا الجهاز: ${usage}`} /><SettingRow label="حفظ سجل القراءة"><Switch checked={preferences.history} onCheckedChange={(value) => update("history", value)} /></SettingRow><div className="danger-actions"><button onClick={() => void clearOffline()}>مسح محتوى دون اتصال</button><button onClick={() => void clearAll()}>مسح كل بيانات التطبيق</button></div><div className="privacy-note"><Shield /><p>المحفوظات والسجل والتذكيرات تبقى محليًا في وضع الضيف. لا نرسل الموقع الدقيق أو عناوين التذكير إلى التحليلات.</p></div></TabsContent>
    </Tabs><p className="sr-status" aria-live="polite">{message}</p></main>;
}

function SettingHeader({ icon, title, description }: { icon: React.ReactNode; title: string; description: string }) { return <header className="setting-header"><span>{icon}</span><div><h2>{title}</h2><p>{description}</p></div></header>; }
function SettingRow({ label, children }: { label: string; children: React.ReactNode }) { return <div className="setting-row"><span>{label}</span><div>{children}</div></div>; }
